<?php 
/**
 * Product component for gateway system.
 */ 
include './components/keycheck.php';

include './components/contentchooser.php';
$body_class = "loggedin terms";
include 'header.php';

?>

  <section class="page" style="padding-top: 50px">
    <div class="grid-container">
      <div class="grid-x">
        <div class="small-10 small-offset-1 cell text-center">
          <h1 style="margin-bottom:40px">Terms of Use</h1>
        </div>
        <div class="small-10 small-offset-1 cell">
          <p>LEGAL NOTICE: EVERGREEN WELLNESS PROVIDES THIS SITE AND RELATED SERVICES SUBJECT TO YOUR COMPLIANCE WITH THE TERMS AND CONDITIONS SET FORTH BELOW. PLEASE READ THE FOLLOWING INFORMATION CAREFULLY: Copyright 2016 Evergreen Wellness, LLC. All Rights Reserved.</p>
          <p>All pages within this Internet site (“Site”) are the property of Evergreen Wellness, LLC. Permission (which may be revoked at any time) is granted to download the material in this Site without alterations and for private and non-commercial use only so long as the following copyright notice is included: Copyright 2010, Evergreen Wellness, LLC. All Rights Reserved.</p>
          <p>“Evergreen Wellness,” the “Evergreen Wellness” logo, and our other logos and brands are trademarks and service marks of Evergreen Wellness, LLC. All other trademarks, service marks and logos used in this Site are the trademarks, service marks or logos of their respective owners.  As an Amazon Associate I earn from qualifying purchases.</p>
          <p>THIS SITE, INCLUDING ANY CONTENT OR INFORMATION CONTAINED WITHIN IT OR ANY SITE-RELATED SERVICE, OR ANY PRODUCT OR SERVICE LICENSED OR PURCHASED THROUGH THE SITE, OR ANY SOFTWARE DOWNLOADED FROM THE SITE, IS PROVIDED “AS IS” WITH NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT. YOU ACCEPT THAT ANY WARRANTY THAT IS PROVIDED IN CONNECTION WITH ANY OF THE PRODUCTS OR SERVICES DESCRIBED HEREIN IS PROVIDED SOLELY BY THE OWNER, ADVERTISER OR MANUFACTURER OF THAT PRODUCT AND/OR SERVICE, AND NOT BY EVERGREEN WELLNESS. YOU ALSO ACCEPT THAT YOUR ACCESS TO THE SITE AND/OR RELATED SERVICES WILL NOT BE FREE OF INTERRUPTIONS. YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR YOUR USE OF THIS SITE AND SITE-RELATED SERVICES. NEITHER EVERGREEN WELLNESS NOR ITS SPONSORS ARE RESPONSIBLE OR LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE OR OTHER DAMAGES UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY ARISING OUT OF OR RELATING IN ANY WAY TO THE SITE, SITE-RELATED SERVICES AND/OR CONTENT OR INFORMATION CONTAINED WITHIN THE SITE. YOUR SOLE REMEDY FOR DISSATISFACTION WITH THE SITE, SITE-RELATED SERVICES AND/OR CONTENT OR INFORMATION CONTAINED WITHIN THE SITE IS TO STOP USING THE SITE AND/OR THOSE SERVICES.</p>
          <p>A possibility exists that the Site could include inaccuracies or errors. Additionally, a possibility exists that unauthorized additions, deletions and alterations could be made by third parties to the Site. Although Evergreen Wellness attempts to ensure the integrity and the accurateness of the Site, it makes no guarantees whatsoever as to the correctness or accuracy of the Site. In the event that such an inaccuracy arises, please inform the Evergreen Wellness webmaster so that it can be corrected.</p>
          <p>This Site may contain links to other Web sites operated by third parties (“Linked Sites”). You acknowledge that, when you click on a link to visit a Linked Site, a frame may appear that contains the Evergreen Wellness logo, advertisements and/or other content selected by Evergreen Wellness. You acknowledge that Evergreen Wellness and its sponsors neither endorse nor are affiliated with the Linked Site and are not responsible for any content that appears on the Linked Site. You also acknowledge that the owner of the Linked Site neither endorses nor is affiliated with Evergreen Wellness and its sponsors.</p>
          <p>Although the Site is accessible worldwide, not all products or services discussed or referenced in the Site are available to all persons or in all geographic locations or jurisdictions. Evergreen Wellness reserves the right to limit the provision of any product or service to any person, geographic area or jurisdiction it so desires. You agree to indemnify, defend and hold harmless Evergreen Wellness and its sponsors against any and all claims, damages, costs or other expenses that arise directly or indirectly out of or from (a) your breach of this Agreement, (b) your violation of the Code of Conduct and/or (c) your activities in connection with the Site or Site-related services.</p>
          <p>While using the Site or Site-related services, you agree not to: Restrict or inhibit any other user from using and enjoying the Site and services; Post or transmit any unlawful, fraudulent, threatening, abusive, libelous, defamatory, obscene or otherwise objectionable or harmful information of any kind; Post or transmit any information or software that contains a virus, worm, trojan horse or other harmful or disruptive component; or Post or transmit materials in violation of another party’s copyright or intellectual property rights. Evergreen Wellness has no obligation to monitor the Site or Site-related services for errors or malicious intent by outside sources. However, you acknowledge and agree that Evergreen Wellness has the right to monitor the Site and Site-related services and to disclose any information necessary to operate the Site properly, to protect itself and its sponsors and customers and to comply with legal obligations or governmental requests. Evergreen Wellness reserves the right to refuse to post or to remove any information or materials, in whole or in part, that are unacceptable, offensive or in violation of this Agreement.</p>
          <p>Evergreen Wellness also reserves the right to prohibit any user who, in Evergreen Wellness’s sole discretion, violates the Code of Conduct or other terms of this Agreement from using the Site and related services. Such prohibition may occur without notice to the user. You agree to indemnify, defend and hold harmless Evergreen Wellness and its sponsors against any and all claims, damages, costs or other expenses that arise directly or indirectly out of or from (a) your breach of this Agreement, (b) your violation of the Code of Conduct and/or (c) your activities in connection with the Site or Site-related services. If you wish to license or make purchases of products or services described on the Site, you may be asked by the applicable merchant or service provider to supply certain information, including but not limited to credit card or other payment information.</p>
          <p>You agree that all information that you provide to any such merchant or service provider will be accurate, complete and current. You agree to pay all charges incurred by users of your account and credit card or other payment mechanism at the prices in effect when such charges are incurred. You will also be responsible for paying any applicable taxes relating to your purchases. Moreover, you agree to review and to comply with the terms and conditions of any specific agreement that you enter into with the merchant and/or service provider in connection with the licensing or purchase of any product or service.</p>
          <p>You acknowledge and agree that, by submitting any resource, link, applet, information, content or other materials (“Content”) to Evergreen Wellness, you grant to Evergreen Wellness a nonexclusive, worldwide license to link to, reproduce, distribute, adapt, perform, display and sublicense the submitted Content. Further, by submitting Content to Evergreen Wellness, you acknowledge that you have the authority to grant such rights to Evergreen Wellness. PLEASE NOTE THAT YOU RETAIN OWNERSHIP OF ANY COPYRIGHTS OF ANY CONTENT YOU SUBMIT. If the submitted Content includes or consists of a Java (TM) applet or other software resource, the license granted to Evergreen Wellness shall apply to both object code and source code formats of the applet or resource, and Evergreen Wellness shall have the right under its license to analyze, report on, summarize, and display the source code on it web sites, however Evergreen Wellness will not display the complete source code of your resource unless you grant Evergreen Wellness express permission to do so in the Resource Submission or Resource Update forms. If you submit a resource to Evergreen Wellness and/or you grant Evergreen Wellness permission to display your source code and decide that you no longer want to grant Evergreen Wellness permission to display your source code, Evergreen Wellness will remove the resource and/or the source code from our site(s) after having received a revocation letter via certified mail, to request that the resource and/or the source code (or any other content or software resource) submitted by you, be removed from the Evergreen Wellness web site. Upon receipt of such certified mail notification, Evergreen Wellness will use its best efforts to remove such resource and/or source code from its web site(s).</p>
          <p>This Agreement is entered into in the State of Florida and shall be governed by and construed in accordance with the laws of the State of Florida, exclusive of its choice of law rules. Each party to this Agreement hereby submits to the exclusive jurisdiction of the state and federal courts sitting in Hillsborough County in the City of Tampa in the state of Florida, and waives any jurisdictional, venue or inconvenient forum objections to such courts. In any action to enforce this Agreement, the prevailing party will be entitled to costs and attorneys’ fees. In the event that any of the provisions of this Agreement shall be held by a court or other tribunal of competent jurisdiction to be unenforceable, such provisions shall be limited or eliminated to the minimum extent necessary so that this Agreement shall otherwise remain in full force and effect and enforceable. This Agreement constitutes the entire agreement between the parties hereto pertaining to the subject matter hereof, and any and all written or oral agreements heretofore existing between the parties hereto are expressly canceled.</p>
          <p>This Agreement may be supplemented or modified by any license or other agreement used in connection with any software or other product that you download, license or purchase through this Site (“Other Agreements”). Except with respect to such Other Agreements, any modifications of this Agreement must be in writing and signed by both parties hereto, except that Evergreen Wellness may modify the terms of this Agreement by sending notice to you via e-mail (at the most current e-mail address for you in Evergreen Wellness’s records) fourteen (10) days in advance of the date on which such modification takes effect or by posting notice of such modification on a page of the Site entitled “Legal Notices” or “Legal Information” at least fourteen (10) days before the modification takes effect.</p>
        </div>
      </div>
    </div>
  </section>

<?php include 'footer.php';?>